# uft-8
import os.path

from pythonProject.compact_utils import MultiLanguageComparison
from pythonProject.parser import XMLParser
from pythonProject.utils import getPwd, exportXMLFromExcel, calculateKeyCount, calculateKeyisLack


def cal():
    str = [-48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0, -1, -1, 1, 0, -3, -1, 2,
           0, -5, -1, 4, 0, -7, -1, 7, 0, -9, -1, 9, 0, -15, -1, 21, 0, -9, -1, 25, 0, -1, -1, 17, 0, 13, 0, -2, -1, 29,
           0, -34, -1, 65, 0, -74, -1, 119, 0, 122, -1, -78, 0, 58, -1, -3, 0, -24, -2, 74, 1, -82, -2, 93, 1, -34, -2,
           -114, 0, -125, 35, -88, 45, 96, 46, 36, 60, -92, 47, -51, 55, 76, 44, 75, 25, -107, 37, 60, 29, 1, 50, -119,
           44, 75, 36, 124, 24, -30, 50, -80, 45, 75, 17, -78, 54, -107, 29, 87, 21, -14, 32, -52, 48, 2, 25, 53, 24,
           116, 42, -106, 26, 53, 23, 104, 20, -57, 44, 126, 36, -96, 9, 22, 41, 11, 39, 103, 11, -71, 45, -115, 41,
           -78, 23, 126, 32, -122, 23, 36, 28, 57, 14, -51, 28, 110, 31, -1, 14, -53, 30, -100, 36, -59, 19, -20, 28,
           47, 44, 22, 21, 4, 31, 85, 36, 39, 34, 56, 22, -28, 24, -17, 38, 123, 17, -101, 27, -89, 30, -63, 13, 70, 32,
           -68, 29, -68, 19, 6, 19, -60, 22, 42, 32, 67, 23, -91, 33, -9, 21, -55, 0, 33, 19, -89, 18, -75, 7, -7, 30,
           76, 5, 2, 27, -46, 38, 53, 7, -45, 23, -36, 14, -40, 20, -79, 12, 124, 7, 13, 14, -121, 1, 35, 10, 109, 11,
           -29, 11, 58, 21, -55, 16, 66, 15, -52, 8, -94, 17, -3, 26, 61, 10, 45, 15, -25, 18, -62, 8, -80, 3, 55, 17,
           104, 15, -35, 9, 73, 22, 42, 18, 46, 12, 110, 13, 103, 11, 101, 1, -83, 6, -52, 16, 56, 12, -48, 7, -20, 27,
           -26, 16, 32, 4, 50, 7, 70, 10, -31, 15, 93, 17, 55, 13, 47, 6, 9, 9, 76, 7, -90, 4, 114, 6, 73, 6, -115, 5,
           -96, 2, -116, 6, -59, 13, -93, 4, -18, -1, -53, 17, 67, 14, -111, -1, 22, 18, -2, 15, 18, -1, -82, 15, -36,
           19, -5, 1, 94, 12, -111, 16, 100, 6, 62, 15, 43, 8, 119, 7, -15, 11, -37, 16, 14, 24, 110, 4, -89, 7, 82, 8,
           125, 4, 117, -1, -16, 6, -10, 14, -57, 6, 98, 17, -52, 12, -1, 10, -32, 15, 118, 13, -62, 11, 105, 16, 13, 8,
           -68, 21, 80, 28, -63, 21, -53, 22, 100, 10, -43, 10, 105, 16, 56, 23, -17, 14, 77, 13, -98, 25, 40, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    print(len(str))
    pass


if __name__ == '__main__':
    # MultiLanguageComparison.compact2(os.path.join(getPwd(), "comp"), "zh_final.xml", "strings-es.xml", "es_final.xml",
    #                                 XMLParser())
    MultiLanguageComparison.compact2(os.path.join(getPwd(), "comp"), "zh_final.xml", "strings_es.xml", "es_final_sort_new.xml",
                                    XMLParser())
    # MultiLanguageComparison.compact2(os.path.join(getPwd(), "comp"), "zh_final.xml", "strings_pl.xml",
    #                                  "pl_final_sort_new.xml",
    #                                  XMLParser())
    # MultiLanguageComparison.compact2(os.path.join(getPwd(), "comp"), "zh_final.xml", "strings_pt.xml",
    #                                  "pt_final_sort_new.xml",
    #                                  XMLParser())
    # MultiLanguageComparison.compact2(os.path.join(getPwd(), "comp"), "zh_final.xml", "strings_en.xml",
    #                                  "en_final_sort_new.xml",
    #                                  XMLParser())
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 1, os.path.join(getPwd(), "strings_zh.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 2, os.path.join(getPwd(), "strings_en.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 3, os.path.join(getPwd(), "strings_es.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 4, os.path.join(getPwd(), "strings_it.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 5, os.path.join(getPwd(), "strings_pl.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 6, os.path.join(getPwd(), "strings_de.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 7, os.path.join(getPwd(), "strings_nl.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 8, os.path.join(getPwd(), "strings_fr.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 9, os.path.join(getPwd(), "strings_pt.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 10, os.path.join(getPwd(), "strings_hu.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 11, os.path.join(getPwd(), "strings_da.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 12, os.path.join(getPwd(), "strings_nb.xml"))
    # exportXMLFromExcel(os.path.join(getPwd(), "AigoSmart_app_2.0.4.xlsx"), 13, os.path.join(getPwd(), "strings_sv.xml"))
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "zh"), "strings-zh.xml", "strings_zh.xml", "zh_final.xml",XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "de"), "strings-de.xml", "strings_de.xml", "de_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "zh"), "strings-zh.xml", "strings_zh.xml", "zh_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "en"), "strings-en.xml", "strings_en.xml", "en_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "es"), "strings-es.xml", "strings_es.xml", "es_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "fr"), "strings-fr.xml", "strings_fr.xml", "fr_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "hu"), "strings-hu.xml", "strings_hu.xml", "hu_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "it"), "strings-it.xml", "strings_it.xml", "it_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "nb"), "strings-nb.xml", "strings_nb.xml", "nb_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "nl"), "strings-nl.xml", "strings_nl.xml", "nl_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "pl"), "strings-pl.xml", "strings_pl.xml", "pl_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "pt"), "strings-pt.xml", "strings_pt.xml", "pt_final.xml",
    #                                 XMLParser())
    # MultiLanguageComparison.compact(os.path.join(getPwd(), "sv"), "strings-sv.xml", "strings_sv.xml", "sv_final.xml",
    #                                 XMLParser())
    # print("2.0.4版本新多语言文档初始条数:" + calculateKeyCount(os.path.join(getPwd(), "total"), "strings_it.xml"))
    targkeys = ["Kitchenap", "Homeap", "Airooler",
                "Portablea", "Currentt", "Cooling",
                "Swing", "Lowspeed", "Mediuspeed",
                "Highpeed", "Coolingm", "Naturam",
                "Sleepinm", "Chiock", "Thewter",
                "Thed", "Thde", "Drymode", "Roomt",
                "Themenurem", "presetth", "Setther",
                "Setthe", "Setth", "toprehea",
                "localnet", "Ensureh", "Ensurethe",
                "Dutch", "Choosade", "Enterhea",
                "accepted", "rejecteyo", "invitedyo",
                "twogatew", "guideline", "Next",
                "homein", "roomin", "devicein",
                "Completegu", "Virtualex", "Devicesre",
                "Enablelo", "localnetw", "Mastesw",
                "switch1", "switch2", "Morervices",
                "unservices", "Firmwrade", "talktoG",
                "Bindinst", "Binddd", "Buyad",
                "LinkAi", "Yousho", "Associate",
                "Enterthea", "ControltCon",
                "Afterasso", "Unbindin", "OpenGoogl",
                "Youcana", "Youshoua", "sswordoAig",
                "OpenAmazon", "Upgrade1", "Fail1",
                "Success", "CountryReg", "EasChina",
                "Eashina", "America", "Southeast",
                "Updatedve", "Ithelat", "Failevice",
                "Setthehome", "Device1", "Batchne",
                "Ifuhavem", "Searchfor", "Afterhesuc",
                "Thereeem", "Trytoreconn",
                "Themobildid", "Tryagai", "Downlo",
                "Downloa", "Downloading", "Updatedve1",
                "Downloadpr", "Downloaaile",
                "Downloadt", "Theupda", "Connectingpo",
                "Checkfo", "Temperatur", "Thetem",
                "Thetempe", "Thankyoqqq", "Foryourno",
                "Agree", "Disagree", "Mobilelo",
                "Emaillog", "Enteryou", "Enteryour",
                "Registe", "Regis", "Cancelqqq",
                "Cancey", "Beforesu", "Youracc",
                "Within1", "Nosmartd", "Youareo",
                "Theaccou", "Within", "adykn",
                "cancellati", "message", "Emailcan",
                "Switchmob", "Thankyo",
                "Informationab", "formatioabou",
                "ccountdet", "logina", "istorymessa",
                "operlrocess", "Confirm", "AigoSmartt",
                "Youraccoun", "Confirm", "Continu",
                "Exit", "Thedevice", "EnterF",
                "Rename", "Current", "Targettemper",
                "Gear", "firsgear", "secondear",
                "Thethird", "Childlocsw", "Childo",
                "Childlock", "Antiro", "Economic",
                "Comfortabl", "Thedevi", "Thdevic",
                "Thedev", "Thedevic", "Thedevicwill",
                "Thede", "omatica", "wiltur", "ouncti",
                "untdowti", "roomavaila", "Refuse",
                "Areousur", "Addcondi", "Addactio",
                "Pleasee", "Copysu", "Youcan",
                "Thisaccoun", "Send", "messagelist",
                "Firmware", "Congratula", "Privacy",
                "Servic", "oclock", "Iagree",
                "Cliennam", "none", "Select",
                "Clicktoswitch", "WIFIconnection",
                "quicklyadddevices", "Compatibility",
                "morestable", "ConnectdeviceWiFi",
                "newhotspot", "returnpage", "Delink",
                "cantfindwifi", "networkmode",
                "Reconnect", "familyname",
                "deviceshared", "Displaye", "Enterth",
                "Chooset", "Pleases", "Pleasese",
                "Home", "Office", "Athome",
                "Leavehome", "Turnonlig", "Turnoffli",
                "Leavetheof", "Nocurrently", "Spain",
                "Italy", "Poland", "Portugal",
                "Britain", "Germany", "France",
                "theUnite", "Undelete", "Deletesu",
                "Saveth", "Postthere", "Pleaseupl",
                "Thecapaci", "Pleasecho", "Switchon",
                "Shareddevices", "Login", "Registera",
                "Reauthentication", "Thelogin",
                "Wehavesent", "Savesuccess",
                "Failtosave", "Successful", "Fail",
                "Myhome", "Thisdevice", "Turnon",
                "Turnoff", "ON_OFF", "Type", "Atatime",
                "Hour", "Minute", "Copy", "Accountnot",
                "Loading", "Deletethis",
                "Viewspecific", "Connecting",
                "Deviceconnection", "Keeprouter",
                "Thephone", "phonelocation",
                "connectedWiFi", "HzWiFi", "Tochange",
                "Continue", "Scene", "Automation",
                "Editthename", "Condition",
                "Conditiontype", "Meetconditions",
                "Task", "Scenenameempty",
                "Conditionempty", "Actionempty",
                "Deviceexist", "Unsupported",
                "Deletscene", "Deleteautomation",
                "Devicethisroom", "Execute",
                "Nodevice", "Addaction",
                "Lackspermissions", "Languagesetting",
                "Personalinformation", "Myroom",
                "Myscene", "Mydevice",
                "Bindmobilehone", "Bindemail",
                "Bindthird", "Facebook", "Twitter",
                "Instagram", "Google", "Pressagian",
                "Codecorrect", "PasswordsPmatch",
                "PupdatedPdata", "FailPrefresh",
                "Haveagree", "Keeppossible",
                "Networkerror", "Followystem",
                "SmartEnjoy", "Functionalexperience",
                "Clicktoview", "Deviceoffline",
                "Smartlighting", "Brightnessvalue",
                "Daylightpattern",
                "Colorfullightpattern", "Smartsocket",
                "Smartswitch", "Gohometurn",
                "Leavehometurnoff", "Findnewdevice",
                "Findthefollowi", "Devichabeen",
                "Report", "Deletethere", "Release",
                "ReportRea", "Correctreasonto",
                "Advertisin", "Porn", "Picturesartic",
                "illegalinfo", "Othersabuse",
                "Deletethepo", "Submitforr",
                "Inreview", "Writesomethi",
                "Reachthemaxim", "Whenanyofthese",
                "Automaticoperati", "Addautomat",
                "Turnonlight", "Mainswitch",
                "Changebackgro", "Addthesence_titl",
                "Whenitmeets_to", "Executethefo",
                "Arrivedepart", "Sunriseand",
                "Currentcity", "Sunrise", "Sunset",
                "Departsomewhere", "Arrivesomewhere",
                "Offline", "Addasence", "StatusOn",
                "Leftslidetounassoc", "Chooseacover",
                "Recommended", "Subscribe", "Search",
                "Category", "Nobloggernotes", "Users",
                "Recipe", "Unsubscribe", "Follow",
                "Device", "Subscriber", "Note",
                "Favorite", "Recipecategory",
                "Morerecipe", "intelligentoven",
                "Airfryer", "Blenders", "Juicer",
                "Pastamachine", "Breadmakers",
                "Electricgrill", "Grill", "Oven",
                "Fryingpan", "Pressurecooker",
                "Slowcooker", "Soupmaker",
                "Electricsteamer", "Saucepan",
                "Others", "Hottest", "Latest", "Video",
                "History", "Delet", "Deleted", "Share",
                "Shareto", "Notenumber", "Ingredients",
                "More", "Seemorereviews", "One_click",
                "Thedevicehas", "Cancel", "Yes",
                "Currentsetting", "Revise",
                "Selecttemperature", "Selecttime",
                "userscomments", "Seeallreplies",
                "Comment", "Reply", "Submit",
                "Releaserecipe", "Enterrecipetitle",
                "Pleaseenterrecipetitle",
                "Goodtitleisessential", "Preview",
                "Addvideopictures", "Enteringredients",
                "Enterdosageforexample",
                "Addingredients", "Cookers",
                "optional", "Step", "Addsteps",
                "Addpictures", "Picturesorvideo",
                "Recommendedtoclassification",
                "recipesummary", "Pleasecompletefirst",
                "Close", "Released", "Check",
                "Sharetoo", "Myfamily",
                "Householdmanagement", "Workingq",
                "Alldevices", "Livingroom", "Kitchen",
                "Bedroom", "Diningroom", "Study",
                "Intellegence", "Add",
                "Nodevicepleaseadd", "Adddevice",
                "Displayinsquare", "Displayinlist",
                "TIPS", "Pleasereconnectyour", "Edit",
                "pdevices", "Addrooms", "Finish",
                "Save", "Roomname",
                "Pleaseinputroomname",
                "Secondarybedroom", "Vestibule",
                "Balcony", "Childrensroom",
                "Cloakroom", "Kitchenappliances",
                "Lighting", "Electricalsupplies",
                "Smallkitchenappliances", "Bulb",
                "TableLamp", "Walllamp",
                "Filamentlamp", "Downlight",
                "Ceilinglamp", "Stiplight",
                "Panellight", "Germansocket", "Switch",
                "Adapter", "VDEsocket", "Fans",
                "Heater", "A_Cmate", "AddWifi",
                "Enterwifipassword",
                "Supports24GWi_Finetworkonly",
                "Giveupaddingdevice",
                "Devicehasbeenadded", "Deviceadded",
                "Shutoff", "Currentdeviceoffline",
                "Wakeup", "Standby", "Fries", "Shrimp",
                "Pizza", "Drumstick", "Fish", "Steak",
                "Cake", "Bacon", "Temperature",
                "Cooking", "Iwanttopresettime",
                "Adjust", "Cookingtemperature",
                "Cookingtime", "RemainingTime",
                "Pre_heat", "Keepwarm",
                "Makeanappointment", "Recipee",
                "Programmed", "Clicktostart", "Offf",
                "Itisnotallowedtocookinpreheat",
                "Itisnotallowedtochange",
                "Thedeviceisoffline",
                "Thelidisopencloseittocontinue",
                "Thedevicehasnonetwork", "DIYrecipes",
                "NoDIYrecipescreated", "Recipename",
                "Recipepictures", "Recipenotes",
                "Delete", "Startcooking",
                "Cookingclicktostop", "Moresettings",
                "Deviceinfo", "Devicename",
                "Deviceposition", "Nosetting",
                "Otherinfo", "Sharingdevice",
                "Deviceinfoo", "QA",
                "Addtoyourmobiledesktop",
                "Firmwareupgrade", "Removethedevice",
                "Restorefactorysettings",
                "Areyousuretoremovethedevice",
                "WarningRemovethedevice",
                "Addasharedlibrary", "Devicesharing",
                "Nodevicepleaseaddd",
                "Ifheisthepermanent", "Familysettings",
                "Enterphonenumber",
                "Dearyoucannotinvite",
                "Thecurrentuserhas",
                "Thecurrentuserhasalready",
                "Deartheaccountisnot",
                "Thedevicehasbeen", "VisualID",
                "IPaddress", "MACaddress",
                "Devicetimezone", "Signalintensity",
                "Clickthebuttonatthe",
                "Selecttoaddtothemainscreen",
                "Quickaccessicon",
                "Findanewdevicefirmware",
                "Findanewfirmwarepleaseup",
                "Wifimodule", "MACmodule",
                "Upgradenow", "Thisisthelatestversion",
                "Findanewversionversion", "Upgrade",
                "Upgradenotices",
                "Itmaytakealongtimeto",
                "Startupgrading", "Firmwareinfo",
                "Upgradingtoversion",
                "Pleasekeepthepowerof",
                "Thedeviceisnotavailable", "Upgrading",
                "Firmwareupgraded",
                "Devicefirmwareupgraded",
                "Multifunctionaloven", "Bake", "steak",
                "toaster", "chicken", "VDEsockett",
                "Socketison", "Socketisoff",
                "Countdown", "Timing",
                "Thedevicewillbeon",
                "Thedevicewillbeoff", "Startin",
                "Endin", "Savechanges", "Timererrors",
                "On", "Monday", "Tuesday", "Wednesday",
                "Thursday", "Friday", "Saturday",
                "Sunday", "Everyday", "Weekend",
                "Workday", "Addthetiming", "Timeron",
                "Timeroff", "Time", "Repitition",
                "Mon", "Tes", "Wed", "Thu", "Fri",
                "Sar", "Sun", "Allon", "Alloff",
                "Thedevicewillbeono",
                "Thedevicewillbeoffo", "Adaptere",
                "Adapterisoff", "Adapterison",
                "Extensionsocket", "Switch1",
                "Switch2", "Switch3", "Switch4",
                "Intelligentbulb", "Touchtoswitchon",
                "Touchtoswitchoff", "Whitelight",
                "Colorama", "Mode", "Lightness",
                "Heating", "Addmodes", "Goodnight",
                "Reading", "Working", "Leisure",
                "Softlight", "Colorful", "Dazzling",
                "Gorgeous", "Changemodepicture",
                "Reset", "Modename", "Modecolor",
                "Colorchangemethod", "Static", "Hop",
                "Breathe", "Submittosave",
                "Colorchangespeed", "Colors", "Slow",
                "Fast", "Colortemperature", "Towerfan",
                "Speed", "I", "II", "III",
                "Oscillating", "Workmode",
                "Naturalwind", "Sleepwind",
                "Brainsmode", "Clicktologin",
                "Loginformore", "Intelligentdevice",
                "Familyinfo", "Roommanagement",
                "Scenemanagement", "Devicemanagement",
                "Communitylife", "Myfollowings",
                "Mydrafts", "Mynotes", "Myfavorite",
                "Settings", "Wipecache",
                "APPnotification", "Accountsafety",
                "Regionselection", "MainlandChina",
                "Chinese", "Spanish", "Italian",
                "Portuguese", "French", "German",
                "Polish", "English", "Useragreement",
                "PrivacyPolicy", "Helpcenter",
                "Sharingapp", "About", "Version",
                "Logout", "Clearingthecachewont",
                "Enteremailphonenumber",
                "Enterpassword", "Signinlogin",
                "Forgetpassword", "Register",
                "Theusernameyouentere",
                "Theemailyouenteredisin",
                "Enterpasswordd",
                "Graphicverificationt",
                "Yourcurrentaccounti",
                "Pleaseenterverifi",
                "RegisterGreatJacob",
                "CountryRegioncannotbe", "Enteremail",
                "Ihavereadandagreeto", "Signupnow",
                "Switchtophoneregistration",
                "Pleaseenterphonenumber",
                "Switchtoemailregistration",
                "Wehavesentaverification",
                "Pleaseenterverif",
                "Enterverificationcode", "Sendagain",
                "Nextstep", "Unregister",
                "hasbeenregistered", "Gologin",
                "Yourregisteredemailis",
                "Pleasesetyourpassword",
                "Pleaseconfirmpassword",
                "Use8_20characterswi",
                "Yourregisteredphone",
                "Theemailformatis", "Theemailistool",
                "Theemailhasa",
                "Servererrorpleasetrylater",
                "Messagehasreache",
                "Theverificationco",
                "Verificationcode",
                "Pleaseenterverifid",
                "Messagehasreached",
                "Thepasswordformat",
                "Thepasswordshoul",
                "Twopasswordsyouen",
                "Registrationfaile",
                "Thephonenumberhasalr", "Pleaseentert",
                "Setpassword", "Setpasswordafterrece",
                "Pleaseenterphone",
                "Verificationmessage", "Setpasswordf",
                "Enteremaild", "Verificationemail",
                "Wehavemessagedaveri",
                "Wehaveemailedaverifi",
                "Thedeveloperwillaquir",
                "Aquireyourpublicinfo",
                "LoginaccounttryGreat",
                "accountsecurity", "Bindamobilephone",
                "Bindingemail", "Password",
                "Bindathird_partyaccount", "Unbound",
                "Removebinding", "Removebindingd",
                "Youarenotallowedtologi",
                "Enablemessagepush", "Notification",
                "Warning", "Interruptbytime",
                "Receive", "Reject", "Help",
                "Feedback", "ReportaProblem",
                "Enterquestions", "Pleasedescribe",
                "Contactoptional", "Pleaseenteryourph",
                "Setthedateandtimewhentheproblemoccurs",
                "Uploadpictures",
                "Pleasewritethetitleor",
                "EditAccountInfo", "Changeimage",
                "Nickname", "Gender", "Male", "Female",
                "Birthday", "Selectbirthday",
                "personalizedsignature", "Snapping",
                "Selectfromphotoalbum", "year",
                "month", "date", "Entername",
                "Enterpersonalizedsignature", "Giveup",
                "Saved", "Familyname",
                "Familyposition", "Devicenumber",
                "Currentdevic", "Familymember",
                "Familymembersandsh", "Delectfamily",
                "Thehouseholddevices", "Administrator",
                "Member", "Createfamily", "Transfer",
                "Addfamilymember", "Addupmost10famil",
                "Thehouseholddevi", "Theadministrato",
                "Doyoutransferadmi",
                "Enterhis_hermobile",
                "Enterthemobilenumb", "Invite",
                "Thephonenumberyou",
                "Thephonenumberyo",
                "Successfullyinvite",
                "He_shehassaved5fa",
                "invitesyoutojoin", "wind_speed",
                "Found", "Networkconfi", "Draft",
                "Pleaseente", "Pleasinp", "Searching",
                "todelete", "tocancel", "Nointerested",
                "Nointerest", "Pleaseenabl",
                "Pleaseenable", "Pleaseenablet",
                "searchtimeout", "Pleaseconfirm",
                "failafte", "Switchmode", "Tryagain",
                "Faitoadd", "Bluetoothod",
                "devicsupports", "Followed", "Shrink",
                "Bluetoothmode", "trytoBlu", "Followe",
                "Unsav", "Recommende", "Requestfa",
                "Shoal", "Showmo", "APPvoic",
                "Devicevoi", "Sensitivity", "Addd",
                "Creat", "Changth", "Newcene",
                "Changew", "Stephang", "Graduachange",
                "configuratio", "Thecloser",
                "WIFI6wireless", "Maksure",
                "bestistance", "Videofiles", "Feedbac",
                "Colorte", "Beats", "Sto", "Norm",
                "Soundsource", "Phonesource",
                "Devicesource", "Typ", "Striplight",
                "Networknoma", "micronotset",
                "Insufficient", "Insufficientc",
                "Devicereminder", "Messag",
                "Newcommen", "Clicktoh", "Iyoue",
                "Thanksi", "ckecords", "Updatee",
                "Discoveran", "Yourecipe",
                "Yourrecipe", "Anewint", "Refust",
                "Pleaselogin", "oldpassword",
                "newpassword", "newpasswora",
                "Wrongoldpas", "newpasswor", "amode",
                "Updatedversion", "categoryonly",
                "Permissionre", "Necessarp",
                "Theapplicat", "Theapplicatio",
                "needscamera", "Theapplication",
                "Theapplication1", "Goforconfigurate",
                "Openao", "Openaoq", "Renew",
                "Expiration", "Videocloud",
                "servicactivated", "Safstorage",
                "aarestored", "Doublen", "Usingfina",
                "Forcurren", "Packagp", "Experi",
                "Saveth1", "daysincid", "daysincida",
                "daysincia", "daysincids",
                "daysincidf", "daysincidj",
                "daysincidg", "daysincidh",
                "daysincidk", "USD", "Euro", "Switche",
                "Packagchange", "serviperiodo", "Goin",
                "Servicime", "Servicaime",
                "Recordingm", "Usableti", "Savethe",
                "uninterr", "orderwas", "Ordeamount",
                "Cheche", "Backtoh", "Failtopay",
                "Ionfirmt", "Purchasnoted",
                "Remainingspace", "Voicprompt",
                "Alarettings", "Chooseo", "aytrigger",
                "Camers", "Backh", "Recordi",
                "Voilarm", "Setsuccessfully",
                "Everydafrom", "detectecross", "UHD",
                "ecordinsett", "eadjustth",
                "Addaprese", "characters",
                "camerastarts", "Nvideo", "Pleaseaim",
                "DomeCamera", "sealedenvironment",
                "Deviceu", "upgra", "Gotit",
                "Pleaschec", "Thearticle",
                "Recommendeecipes", "Camera", "zb",
                "ipc_main_warm_use_phone_traffic",
                "ipc_main_definition_high",
                "ipc_main_definition_normal",
                "ipc_main_can_intercom",
                "ipc_main_intercom_redio_err",
                "ipc_main_intercom_close",
                "ipc_main_record_fail",
                "ipc_main_record_err_io",
                "ipc_main_record_success",
                "ipc_main_record_save_path",
                "ipc_main_record_play",
                "ipc_main_record_save_fail",
                "ipc_main_snapshot_fail",
                "cruise_on_tip", "cruise_off_tip",
                "drag_set_detection_area", "level_low",
                "level_medium", "level_high", "week",
                "code_28504",
                "get_sd_information_fail",
                "video_load_error",
                "video_load_playback", "no_record",
                "your_device_have_no_sdcard",
                "insert_sdcard_need_restart",
                "your_device_have_no_disk",
                "insert_disk_need_restart",
                "no_look_cloud_record_permission",
                "no_look_sd_record_permission",
                "record_date_bigger_than_today",
                "local_device_conn_error",
                "get_info_error", "control_mode",
                "timing_control", "auto_control",
                "manual_control", "manual_switch",
                "night_mode", "full_color_night",
                "infrared_night",
                "intelligent_infrared_night",
                "enable_time", "lighting_delay",
                "night_vision_mode",
                "auto_switch_night_mode",
                "auto_switch_night_mode_detail",
                "always_on_night_mode",
                "always_on_night_mode_detail",
                "always_off_night_mode",
                "always_off_night_mode_detail",
                "call_settings_2", "call_settings_3",
                "call_settings_4", "call_settings_5",
                "call_hfmrsz", "call_settings_6",
                "call_settings_7", "call_settings_8",
                "tv_console", "tv_presetting_bit",
                "scan_match_net",
                "scan_match_net_use_code",
                "click_to_big_code",
                "not_receive_sound",
                "device_match_net", "device_position",
                "history_files", "camera_setting_yfw",
                "camera_setting_wkt",
                "camera_setting_lxycc",
                "camera_setting_bjsz",
                "camera_setting_yshw",
                "camera_setting_yszd",
                "camera_setting_thsz",
                "camera_setting_aqmm",
                "camera_setting_ytbz",
                "camera_setting_gxsb",
                "camera_setting_sbxx",
                "camera_setting_jcgjsj",
                "camera_setting_sbjbxx",
                "camera_setting_sbpz",
                "camera_setting_qtxx",
                "camera_setting_ycsb", "bjgl_bjgl",
                "bjgl_bjxxjg", "bjgl_bjsy", "bjgl_qfs",
                "bjgl_zdysy", "bjgl_fz", "bjgl_ydzcbj",
                "bjgl_ydzc", "bjgl_zcdhmyr",
                "bjgl_qyzcbj", "bjgl_zcdyrw",
                "bjgl_yjzcbj", "bjgl_rxzcbj",
                "bjgl_zdrxjxjc", "bjgl_sybj",
                "bjgl_cfbjs", "bjgl_lmd",
                "bjgl_zcsjsz", "bjgl_zcqysz",
                "bjgl_rxdx", "tv_time_time",
                "local_file", "no_files", "check_all",
                "check_none", "tv_time_video",
                "tv_cruise_function", "tv_ipc_del_pic",
                "motion_detect_alarm_tip", "today",
                "yesterday", "delete_files_sure",
                "clear", "detection_area",
                "scene_mode", "indoor_mode",
                "outdoor_mode", "trigger_mode",
                "trigger_direction", "trigger_in",
                "trigger_out", "trigger_in_out",
                "blink_enable", "vg_rect_alarm_tip",
                "vg_line_alarm_tip",
                "human_detect_alarm_tip",
                "environmental_sensitivity",
                "human_mark_enable", "indoor_human",
                "outdoor_human", "outdoor_car",
                "detect_time", "mode_fullday",
                "mode_nighttime", "mode_custom",
                "fullday_time_tip", "mode_daytime",
                "next_day", "ccsz", "ccsz_bjlx",
                "ccsz_dsbcfbjs", "ccsz_dslx",
                "ccsz_dskqlxbbb", "ccsz_sjdsz",
                "ccsz_lxzl", "ccsz_cckxx",
                "ccsz_wjcdsdk", "ccsz_rgycrsd",
                "ccsz_gshsdk", "rxzc_size_tip",
                "start_time", "end_time", "time_date",
                "detect_custom", "repeat",
                "access_password_hint",
                "access_password_sure_hint",
                "access_password_set", "jsxthfzcczt",
                "sfsdsbtsy", "Atime", "Mobile",
                "novoice", "notblocked", "powersupply",
                "QRcode", "soundon", "soundoff",
                "Defrost", "Lowtemperature",
                "Hightemperature", "Group",
                "groupexpired", "Edigroup",
                "Deletegroup", "socketpro", "Addgroup",
                "Groupname", "followingdevi",
                "Devicesadde", "devicesthat",
                "experience", "devicesand",
                "Turnspecific", "specificdevices",
                "reopenin", "Enabledsu", "Pushmessage",
                "Enablepush", "toenable",
                "pushmessages", "Pushperiod",
                "Pushday", "Pushtime", "Alarmessages",
                "Homemessag", "Systemmessag",
                "Switchdevice", "Checexample",
                "ebanner", "Autdiscover", "Afteenable",
                "bannershown", "bannerhidden",
                "Turnedsuc", "Unknownus", "Wrongld",
                "passwordnot", "Nepasswor",
                "AuAgreement", "Privaclicy",
                "Noavailable", "wrong10", "wrong9",
                "wrong8", "wrong7", "oncenly",
                "Cloudtor", "Ordedoe", "noexist",
                "recipeha", "accounthas", "satisfiedw",
                "Yountere", "IPCQRcode",
                "Curtainswitch", "Onevice",
                "Steamairfryer", "Airoven", "Searc",
                "enrollment", "Initialize",
                "newrmware", "Adjus", "fastercontrol",
                "zonealibration", "changethetime",
                "Devicelanguage", "devicwillestart",
                "Startavirtua", "tv_night_mode",
                "tv_night_mode_des", "tv_colours_mode",
                "tv_colours_mode_des", "tv_smart_mode",
                "tv_smart_mode_des", "Whenon",
                "Countryregion", "Pleaseselect",
                "Attention", "advisedenable",
                "addeddevice", "Youadvised",
                "Whenenabled", "locatpermissions",
                "ocationservice", "discovernew",
                "Toenable", "TOP", "Recip", "Discover",
                "Talents", "Activeusers", "Hotecipes",
                "Follo", "Unfollo", "recipes",
                "followers", "Removedrom", "Savedto",
                "Createc", "Requiredfi", "Requirefi",
                "Shareh", "Changcover", "Cover",
                "followertotal", "Reci", "Setcurtain",
                "Lonress", "Turnhe", "Rotate",
                "Baking", "Driedfruit", "Fih", "Rheat",
                "Deydrate", "Shrmp", "Steamingo",
                "Airfrying", "Seleaning", "Steamin",
                "lackwater", "Recipcollection",
                "Recipeescription", "Savecollections",
                "Removecolle", "selectcover",
                "Popularcountr", "Opencurtain", "Lik",
                "Comm", "Toautho", "Buzze",
                "Duringrui", "aDuring", "bDuring",
                "cDuring", "cannotmpty",
                "conditionshange", "Qcode", "Blueto",
                "curtain_stop", "checknetwork",
                "LogAmazon", "AlreadyAlexa",
                "vocontrol", "Rgin", "Back",
                "Authorization", "Authorizationc",
                "Accessinformation", "Accessright",
                "notpported", "DeauthorizAlexa",
                "Afterunbind", "Unbindi", "Bindin",
                "caneauthorize", "Confirmau",
                "Refuseau", "Startcalibration",
                "Calibrationins", "statuormal",
                "curtaiecuted", "willperform",
                "Timealibration", "Complet",
                "Recalibrate", "Lastlibration",
                "devicbound", "Faigain",
                "periodetting", "Starttime",
                "Finisime", "patiently",
                "Wireonfiguration", "deviceonnected",
                "Powerdevice", "ScanQR", "sbeingup",
                "Stores", "Swipeup", "Swipedown",
                "Youregoing", "Googlemap", "Applemap",
                "ordemake", "LongD", "Nomap",
                "Pleaseset", "HU", "HUN",
                "tsencouragement", "giveusa",
                "yoursupport", "Toencourage", "Notnow",
                "Platformreply", "Updatenow",
                "Morversion", "notpop", "Calolume",
                "Memorynction", "Memoryfu",
                "powerailu", "powage", "powerups",
                "Remembat", "Curtainalib", "Pleasen",
                "hisversion", "Versionnotice",
                "locklocked", "Precompleted",
                "Shanghai", "Singapore", "Unknown",
                "stillevices", "failedreason",
                "calibration", "Turntion",
                "motorswitched", "devicepower",
                "devicesupp", "Tosol", "cannotwork",
                "Currenthumidity", "wateull",
                "nameagain", "viewedappr", "Automati",
                "Promo", "notppear", "Procampaign",
                "Elecettle", "Heatingg", "Coolingr",
                "Keepiarm", "Cooboiling",
                "Heatingwarm", "Targetature",
                "Cooliling", "Keeprature", "Keeptime",
                "Milkowder", "Whitea", "Greeea",
                "Instanffee", "Blacea", "Scentetea",
                "Boilinmode", "Heatinmode", "Theturn",
                "Thurn", "Ceilinglight", "Theannd",
                "Recipeo", "backapp", "Salesman",
                "Sigully", "entersalesman", "Oniling",
                "Boilinwarm", "notexecuted",
                "Enterpasswo", "Keepingwar",
                "Electriettle", "Selectkettle",
                "Rhythm", "Exirhythmode",
                "Linkaddress", "Mailcode",
                "notnotifications", "Brandtation",
                "branddevic", "Vcode", "WiFigement",
                "Savwifi", "AddWiFi", "deviceanno",
                "ConnectWiFi", "RWiFi",
                "Operatompleted", "Comfiretion",
                "WiFianagement", "ModifWiF",
                "Deviceound", "performedworking",
                "ECOmode", "Youincorrect",
                "Activitdoeexist", "ifinfringement",
                "Whethecommonly", "Standardmode",
                "Classimode", "Jazmode", "ROCmode",
                "Inpower", "Takcolor", "Pickimage",
                "Phoarea", "Selectpicture",
                "algorithmnd", "Usecolors",
                "Recalculate", "Image", "Cleaningobot",
                "Partitionleaning", "Wholecleaning",
                "Zonecleaning", "Spoleaning",
                "Cleaninode", "Currentatus", "Worki",
                "Chargin", "Pause", "Sleeping",
                "Areacleane", "Formore", "Cleaningset",
                "Quiet", "Standard", "Strong",
                "Automatic", "Deviceolume",
                "LocatRobot", "Schedcleaning",
                "Manualcontrol", "Lightswitch",
                "Dodisturbmode", "Canagement",
                "Cleaningecords", "Mapmanagement",
                "Dustmanagement", "Unitset",
                "Resetorders", "Maprestore",
                "Restoremap", "placechargin",
                "Haslaced", "Asweep", "robotstarts",
                "Pleasemap", "Voicevolume",
                "Volumeset", "languageupdated",
                "robotsound", "Clickrobot",
                "collectdust", "Dustcollection",
                "Nodustcollect", "Collectdust",
                "Collectduste", "Collectdusteq",
                "Collectdustew", "Collectduster",
                "Collectdusteqt", "Collectdusteqy",
                "Accumulatedtime", "Accumulatedrea",
                "Accumulatedtimes", "cleaningrecord",
                "Cleaningarea", "Workinglength",
                "NOGOZone", "Moisturelevel",
                "scheduledcleaning", "Cleaningtim",
                "Faeled", "Favouanceled", "Mmap",
                "Usemap", "Mapuse", "Map",
                "lifeelement", "Remaininglife",
                "lifebrushes", "lifebrush", "lifemop",
                "workedor", "minemained",
                "brushesused", "calculationreset",
                "customerservice", "Sidebrushes",
                "Filterelement", "Mainbrushes", "Ligh",
                "Whenturned", "WiFiexists",
                "WiFilimit", "Theselectedneaw",
                "lookcharg", "Therificationya",
                "Errorode", "whethap", "Enterame",
                "Cleanitails", "Workinglengthww",
                "remotrol", "Cleaningareaw",
                "Whenation", "Ordinary",
                "Roomearacters", "Thiomnaming",
                "lowadedd", "midged", "upscaled",
                "twiced", "Baarging", "staingff",
                "Incoword", "Usexist", "ahourswrong",
                "accountocked", "Pleaseen",
                "Failnetwork", "currentccoun",
                "havelogging", "ccountlready",
                "Verification", "Incorrecterification",
                "againours", "Canreceive", "Passwor",
                "passwordsentt", "Lissorting",
                "Modificatioshar", "Curremodi",
                "deviceroces", "etectedke", "Signow",
                "Cleaninmes", "Takngnd", "Suctiourin",
                "Takecthen", "Cleaall", "Partition",
                "Merge", "Invalidrgetion",
                "Invalidtitiope", "Renamew", "Unnamed",
                "Whetherthe", "Descriptionhe",
                "Status", "Suction", "Cistern", "Erro",
                "Addmaximum", "Addmaximumzones",
                "Areaddehenge", "Verificationk",
                "Verificatiod", "Verificatiiled",
                "Verificedne", "Verificatioaile",
                "reainvalid", "Incorremae",
                "Pleaseaus", "Pleaselect",
                "Virtuawall", "Noneeee", "Nooneetting",
                "sweepinhine", "Pausleaning",
                "Remainiower", "Workinme", "Colocking",
                "Bluetoprogre", "Notfingerprint",
                "Fingerprintfailed", "Failedagain",
                "APbeempty", "UseID", "Noregistered",
                "Nopassword", "Vfingerprint",
                "fingerprintentry", "Plistration",
                "operated", "Hardwvailable",
                "Thanttempts", "Theggzeration",
                "Theongsss", "Anenage", "Anmagess",
                "devicde", "currenevice",
                "Devicedddded", "Browsposts",
                "Browsosts", "Browspostsl",
                "Browsarticlesosts", "Browsostspp",
                "Browsrticleostsee", "Browseposts",
                "Browseclesostsqq", "Browsiclesposts",
                "Linkountime", "Bindedhome",
                "Youcanhome", "Deauthorizeogle",
                "Afternbindingev", "Biologiccognition",
                "Setgerprinacnlock",
                "Fingerpriunction", "Faceggnction",
                "Fingerctinmpare", "Faceytheposes",
                "Areourfegin", "Arengerprin",
                "Incorreporctiabled",
                "Incorrecfingerdis", "UseAigoSm",
                "PleaseSmart", "Loasswords",
                "Fingenter", "Incorrmonstrat",
                "Profilggg", "Blurrydd", "Facdddred",
                "Incompletedd", "Faceisnter",
                "Areamerang", "Languagwitchi",
                "Faceytheposes", "Areourfegin",
                "Arengerprin", "Incorreporctiabled",
                "Incorrecfingerdis", "UseAigoSm",
                "PleaseSmart", "Loasswords",
                "Fingenter", "Incorrmonstrat",
                "Profilggg", "Blurrydd", "Facdddred",
                "Incompletedd", "Faceisnter",
                "Areamerang", "Languagwitchi",
                "Languagitching", "Devicgradindese",
                "Firmwaselater", "Switchemonctio",
                "Inailurepower", "Aftewerstoreev",
                "Aftowelurstore", "Areturnusic",
                "ArePPode", "Withamringrience",
                "Areffheodeices", "Therevicesoderethe",
                "Turnevices", "Turffthviconly",
                "Theredyange", "Thcurrenlaenaved",
                "Deghtnesshh", "Brightgg", "Darkgg",
                "Offgg", "Berprintharacteri",
                "Blocthor", "Numbields", "shield",
                "Thethato", "Removsfully", "removeqq",
                "Authonickname", "Authovata",
                "moreedback", "reporttitle",
                "Pleaseontent", "Uploadree",
                "uploadage", "Repoccessful",
                "Receivemail", "PKcode", "Youlogin",
                "Youfacelogin", "Canceecharge",
                "Resetleaning", "Resethemap",
                "Leeparatork", "Itmmendeho",
                "Dootmind", "Pleaserrectnumb",
                "Pleasildmarst", "Pleasetehe",
                "Colohangehod", "Linkggg",
                "Replydministr", "Searchingfor",
                "KeepBluetooth", "Unabletoadd",
                "Goods", "Detail", "BUSend",
                "BUSRemainingStock",
                "BUSCustomerComment",
                "BUSOrderFreeFreight",
                "BUSSelectAlready", "BUSInquire",
                "BUSSubscribeSuccess", "BUSdescribe",
                "BUSillustrate", "BUScharacters",
                "BUStopay", "BUSupdate",
                "BUSSearchplace", "BUSConfirmAndPay",
                "BUSgotopay", "BUSAmountspayable",
                "BUStocomments", "BUSViewall",
                "BUSCancelrequest", "BUSReapplication",
                "BUSInvoiceamount", "BUSupdatetime",
                "BUSNologistics", "BUSInviteusers",
                "BUSorderspend", "BUSOrderreward",
                "BUSorderreturn", "BUSAllOutOfStock",
                "BUSSubmitpay", "BUSbuymail",
                "BUSShipmail", "BUSCollectarrives",
                "BUSarrival", "BUSsubscription",
                "BUSRecommended", "BUSflashsale",
                "BUSDetail", "BUSGoods", "BUSHours",
                "BUSSeconds", "BUSOpenParameter",
                "BUSManual", "BUSCCC", "BUSTUV",
                "BUSCertification", "BUSPicturePDF",
                "BUSSpecification",
                "BUSIntallInstructions",
                "BUSReadMoreComment", "BUSOpenDesc",
                "BUSSeeallreviews", "BUSIntroVideo",
                "BUSNoCustomerCommentYet",
                "BUSSubmitSuccess",
                "BUSUploadVideoError",
                "BUSUploadImageError",
                "BUSGoodsDiscontinued",
                "BUSPlaceholderSearch",
                "BUSNosearchhistory",
                "BUSsearchhistory",
                "BUSClearsearchhistory",
                "BUSAllproduct", "BUSempty", "BUSsort",
                "BUSMostcomments", "BUSpricehigh",
                "BUSPricelow", "BUSSaleshigh",
                "BUSSaleslow", "BUSNoproducts",
                "BUSNorelated", "BUSShoppingCart",
                "BUSDeliverTo", "BUSMallCenter",
                "BUSNextCalculation", "BUSSettlement",
                "BUStoggle", "BUSNoGoodsToBuy",
                "BUSVATIncluded",
                "BUSGoodsStockErrorAlert",
                "BUSnoaddress", "BUSaddReceiptaddress",
                "BUSbuygoods", "BUSordercancelled",
                "BUSReasonfail", "BUSreturnorder",
                "BUSallevents", "BUSmymall",
                "BUSgetaigocoins", "BUSNorecord",
                "BUSmycode", "BUSmylink",
                "BUSSwitchCountry", "BUStotalpieces",
                "BUSViewinvoice", "BUSrefailed",
                "BUSSeewhy", "BUSInstructions",
                "BUSNoorders", "BUSInvoiceaddress",
                "BUSreceipttime", "BUSconfirmcancel",
                "BUSconfirmdeletion", "BUSReason",
                "BUSRefund", "BUSdelivery",
                "BUSEditaddress", "BUStransportation",
                "BUSwrongproduct", "BUSbadgoods",
                "BUSRefunds", "BUSthankletter",
                "BUSotherproblems", "BUSEnter",
                "BUSDefaultaddress",
                "BUSwithoutaddress", "BUSentersearch",
                "BUSnotfound", "BUSdeleteaddress",
                "BUSAddShopCartSuccess",
                "BUSShoppingMall", "BUSCategory",
                "BUSAllGoodsOutOfStock",
                "BUSConfirmDeleteOrNot",
                "BUSnoproduct", "BUSpromotionarea",
                "BUSallproducts", "BUSLoading",
                "BUSComment", "BUSFinish", "BUSDays",
                "BUSMinutes", "BUSComments",
                "BUSFreeFreight", "BUSFreight",
                "BUSGoodsDetail", "BUScoding",
                "BUSCollapseparameters",
                "BUSAverageRating",
                "BUSPublishComment", "BUSBuyMoreGoods",
                "BUSCommentfrom", "BUSPeople",
                "BUSCloseDesc",
                "BUSAddGoodsToShopCart",
                "BUSTightStock", "BUSUsingGuide",
                "BUSUseInstallVideo", "BUSAttention",
                "BUSArrivalReminder", "BUSConfirmOK",
                "BUSAnonymousComment",
                "BUSCommentContent",
                "BUSCommentImageVideo",
                "BUSAtleastCommentContent",
                "BUSBackToLast", "BUSMore",
                "BUSSubmit", "BUSClassification",
                "BUSinstock", "BUSfilter", "BUSAll",
                "BUSHasStock", "BUSOutStock",
                "BUSreset", "BUSSelectGoods",
                "BUSDeleteSuccess",
                "BUSCancelCollection",
                "BUSCollectionSuccess",
                "BUSGoodsOutOfStock", "BUSTotalPrice",
                "BUSGoShopping", "BUSOrderSummary",
                "BUSCommoditySubTotal", "BUSdelete",
                "BUSInventoryShortageError",
                "BUSOutofStockError",
                "BUSConfirmAndSubmit",
                "BUSConfirmOrder", "BUSaddress",
                "BUSpayment", "BUSaigocoins",
                "BUScoupon", "BUSEntercode",
                "BUSmyaigocoins", "BUSuse", "BUSpay",
                "BUSaddaddress", "BUSnoshipaddress",
                "BUSpaysuccess", "BUSordernumber",
                "BUSthanks", "BUSinvitationcode",
                "BUSInvitationaddress",
                "BUSInvitationInstructions",
                "BUSInvitationaddress",
                "BUSorderdetails",
                "BUSContinueShopping",
                "BUSPaymentfailed", "BUSpayagain",
                "BUSOrderStatistics",
                "BUSactivitydetails", "BUSprocessing",
                "BUSAboutstart", "BUSover",
                "BUSdescription", "BUSActivitytime",
                "BUSActivity", "BUSAlltopics",
                "BUSInvitation", "BUSMyOrder",
                "BUSMyAddress", "BUSmyinvoice",
                "BUSAllMyComments", "BUSMyCollection",
                "BUSreturnpolicy", "BUScontactus",
                "BUScommonproblem", "BUSincome",
                "BUSexpenditure", "BUScopy",
                "BUSCopysuccessfully", "BUSallorders",
                "BUSbepaid", "BUSbedelivered",
                "BUSShipped", "BUScompleted",
                "BUSCancelled", "BUScancelorder",
                "BUScontact", "BUSReinvoice",
                "BUSApplying", "BUSreturn",
                "BUSEnterorder", "BUSOrderStatus",
                "BUSgoreview", "BUScreationtime",
                "BUSPayamount", "BUSPaytime",
                "BUSdeliverytime", "BUSbuyagain",
                "BUScancelapplication",
                "BUStracknumber", "BUSlogistics",
                "BUSreturnapplication",
                "BUSLoginformation",
                "BUSInvoiceconfirmation",
                "BUSConfirmfol", "BUSUnchangeable",
                "BUSchangeaddress", "BUSconsultation",
                "BUShistory", "BUSSelectcontent",
                "BUSProductDetails", "BUSquestion",
                "BUSAnswer", "BUSname", "BUSsurname",
                "BUSCity", "BUSCounty", "BUScode",
                "BUSTaxID", "BUSPhonenumber",
                "BUSDetailaddress", "BUSSetdefault",
                "BUSsave", "BUSnation", "BUSchoose",
                "BUSenterquery", "BUSnoreceipt",
                "BUSAllcomments", "BUSstar",
                "BUSNoCommentsYet", "BUSAddAllGoods",
                "BUSNoCollectGoodsYet",
                "BUSGoodsAddToShopCartAlready",
                "BUSGoShoppingCart", "BUSaddcart",
                "BUSsavemoney", "BUSundeliverable",
                "BUSThetgood", "BUScannow",
                "BUSItstudhard", "BUSSitposture",
                "BUSWomesj", "BUSenteritle",
                "BUSviewMode", "BUSColorfulight",
                "BUSStaticw", "BUSDynamic",
                "BUSSaveode", "BUSPleaseame",
                "BUSForegrolor", "BUSBackgroolor",
                "BUSFrequenpectrum", "BUSPowerdd",
                "BUSScrolls", "BUSLengtight",
                "BUSIfriencef", "BUSActungth",
                "BUSsmarlamp", "BUSEymode",
                "BUSAutomadjustment", "BUSEfficieork",
                "BUSScreeding", "BUSsmaare",
                "BUSWheinutes", "BUSDelayoff",
                "BUSturelayj", "BUSSlowlyoeout",
                "BUSlightslowly", "BUSBrighotection",
                "BUSWhenbrightness", "BUScaregg",
                "BUSrecordgg", "BUSquickminder",
                "BUSCustomiseoice", "BUSaddrecord",
                "BUSnamerecord", "BUSCustomisedvoice",
                "BUSholecord", "BUSplayhh",
                "BUSapplyhh", "BUSsettinghcare",
                "BUSadjustofarea", "BUSInppears",
                "BUScareimett", "BUScareordsh",
                "BUScargdata", "BUSdateto",
                "BUSthiseekh", "BUSlastjjweek",
                "BUSthesterday", "BUSyesterdayw",
                "BUScaretats", "BUSallrecords",
                "BUStcenmulation",
                "BUSclassrooimulation",
                "BUSexaimulation", "BUSworimulation",
                "BUSworkff", "BUSbreakff",
                "BUSrepeatf", "BUStimesff",
                "BUSCustomiseode", "BUSadmode",
                "BUSWhethernewne", "BUSWhethemode",
                "BUSeditmode", "BUSnameode",
                "BUSworktimemore", "BUSbreakemore",
                "BUSrepeaimes", "BUSWheeriod",
                "BUSWheisplayed", "BUSfactoryeset",
                "BUSWhetheetting", "BUSsurrvicegvg",
                "BUSUnabdevice", "BUSfeedbacks",
                "BUSRetrepsf", "BUSearchingdevices",
                "BUSleasedevice", "BUSnovailable",
                "BUSvicebstructions",
                "BUSAllCategories", "BUScomingsoon",
                "BUStobeconfirmed", "BUSpayreminder",
                "BUSRebateTips", "BUSnewreminder",
                "BUSsuccessused", "BUStransfer",
                "BUSCompanyName", "BUSpaymentreminder",
                "BUSRemitted", "BUSPaymenttime",
                "BUSremittance", "BUSbeconfirmed",
                "BUSNoactivitycount", "BUSoutofstock",
                "BUSdeleteconfirmation", "BUSrecipe",
                "BUSdownloadrecipe", "BUSOrderrebate",
                "BUSupperlimit", "BUSChoosmodes",
                "BUSspeedff", "BUSdeviolidation",
                "BUSreceivedes", "BUSsents",
                "BUSWhetevv", "BUSlastss", "BUSnextss",
                "BUSpictsbum", "BUSSteadn",
                "BUSAutomcution", "BUSIWavintedly",
                "BUSChasinshing", "BUSSlernatends",
                "BUSSckeringb", "BUSSlotendsd",
                "BUSStarrashingsa", "BUSbreathings",
                "BUSsemonlyzz", "BUSStrobez",
                "BUSAuhhon", "BUSAutooff", "BUSHomess",
                "BUSSceness", "BUSGoodsss",
                "BUSGroupss", "BUSmessagea",
                "BUSLabss", "BUSSolaght",
                "BUSbrightness", "BUSrainwemode",
                "BUSRadamode", "BUSsteadynode",
                "BUSTimeoffs", "BUSTurnupd",
                "BUSpetfeeder", "BUSFeedingday",
                "BUSFeedinecords", "BUSFeedinchedule",
                "BUSmanueeding", "BUSfeedinggg",
                "BUSportionss", "BUSSloweding",
                "BUSplayeeding", "BUSNeedoicefirst",
                "BUSAbandoedit", "BUSRecordinoohort",
                "BUSfeedingortion", "BUSFeedingrtions",
                "BUSItortionsf", "BUSlowpower",
                "BUSLowood", "BUSfuckgg",
                "BUSTotaeedings", "BUSNormalwind",
                "BUSDIYenu", "BUSAddYenu",
                "BUSmormenu", "BUScookinghh",
                "BUSpreheating", "BUSPreheatinomplete",
                "BUSPreetting", "BUSpausing",
                "BUSdonggf", "BUSstartds",
                "BUSkeeooking", "BUSstopreheating",
                "BUSstoresetting", "BUSpreheaht",
                "BUStemperaturea", "BUStimess",
                "BUSturveeminder", "BUSmorenusd",
                "BUSKebabd", "BUSvegetables",
                "BUSFeedplantoast1",
                "BUSFeedplantoast2",
                "BUSFeedplantoast3",
                "BUSFeedplantoast4", "BUSDevicryagain",
                "BUSReturnpgrade", "BUSDynamicrr",
                "BUSsmartoicsistant", "BUSShowonly",
                "BUSrecord", "BUSColousitionoff",
                "BUSColouansition", "BUSParticlode",
                "BUSErasemode", "BUSSomeoneringare",
                "BUSReminderturhghts",
                "BUSDurintomaticalhe", "BUSVolumeww",
                "BUSMessagarinreas", "BUSMessagehehen",
                "BUSEntryimew", "BUSWheaimeeo",
                "BUSMessagreas", "BUSMessagerea",
                "BUSRecordrr", "BUSLeavingimeq",
                "BUSWhenngdeo", "BUSRecordmin",
                "BUSMuteee", "BUSInsufficiWater",
                "BUSContinuousww", "BUSIntermittent",
                "BUSFilterplacement",
                "BUSReseilteimer", "BUSEquipmeaning",
                "BUSResleaninmer", "BUSFilterimer",
                "BUSCleaninimer", "BUSReseimer",
                "BUSSharewww", "BUSpurchaseLimit",
                "BUSlimitPerOrder", "BUSlimitreached",
                "BUSCommoditylimit",
                "BUSclearoperation", "BUScantbuy",
                "BUSlimited", "BUSthefollowing",
                "BUSChangequantity",
                "BUSunsubmittable",
                "BUSInventoryshortage", "BUShorsligne",
                "BUSDeviceolume", "BUSPleasugain",
                "BUSEnteumbeID", "BUSPeuntain",
                "BUSInsufficiater", "BUSStaroofte",
                "BUSCookinode", "BUSFinishooking",
                "BUSBinevices", "BUSDiscovices",
                "BUSTiminhange", "BUSTheotherparty",
                "BUSTheaccount", "BUSUserID",
                "BUSoptional", "BUSAllfields",
                "BUSTheproduct", "Clicownload",
                "Doadinggg", "Documenwnloa",
                "Downloleagain", "Isheesvice",
                "Currentltepora", "Specinbounded",
                "Ourroducts", "Recipmmunity",
                "Newrrivalse", "Evenone", "Scenesss",
                "Recommendeprod", "Recommendecipe",
                "Newrrivals", "Historye", "Searche",
                "Nofereneyword", "Searcesults",
                "Searchee", "Warmswitch", "Nighlight",
                "Continuouhum", "Constanhum",
                "humidifier", "environmumidi",
                "ambiemperature", "colorfuhts",
                "coloreights", "warfog", "fixeolor",
                "iliutoma", "iliutomae", "Colorghts",
                "Clors", "Regular", "Spreather",
                "Smooth", "Stream", "Drag", "Flow",
                "Variation", "redw", "whitess",
                "Lighssark", "yellow", "greens",
                "blue", "greenss", "purple", "Forward",
                "reverse", "curtain", "theClosing",
                "fiveColors", "sixColors", "colorfuls",
                "running", "runBack", "RedStatic",
                "GreenStatic", "BlueStatic",
                "Strobeed", "Strobereen", "Strobeue",
                "Strobeolors", "Strobeolorsd",
                "Fadehred", "Fadehgreen", "Fadeffblue",
                "Fadejcolors", "Fadefscolors",
                "Flashdfsed", "Flashareen",
                "Flashdsblue", "Flasholors",
                "Flasolors", "Adjequence",
                "Seligheads", "Cloulight",
                "Wakeerform", "Focushh", "Lavender",
                "Primarcolors", "Nightight", "Comfort",
                "Clouds", "Relax", "Clearkky", "Ocean",
                "Warmth", "Romantic", "Jungle",
                "Missing", "Party", "Rainbow",
                "Energymode", "ightnesime", "Starat",
                "Endat", "Daylighmode", "Sunghj",
                "Staticgdfode", "ightnesingterval",
                "rightnesunsede", "rightnesstofstate",
                "Accounncellation", "Theaccounncor",
                "Incorrpassword", "Fillaccount",
                "Verifydentify", "Confirms",
                "Finishaa", "logiccount",
                "MobilEmaiumber", "thirdpartheuth",
                "Passwordaa", "Entpassword", "Nexstep",
                "embevailable", "SMrificatiode",
                "Senerifide", "Suggestionolatform",
                "Theesothi", "Backvicimeout",
                "Deviceffline", "Devicefflinle",
                "hetheeetwor", "Nmoremind",
                "Devicegaine", "Theviceetec",
                "Alartected", "Controllers",
                "Addddage", "Opendd", "Notdhone",
                "Brightnessdge", "Somesseeds",
                "Indicatoghff", "Turnghtsss",
                "Turnhyights", "Turnjjights",
                "Knobggitch", "switch_environment",
                "Velocity", "BUSPhonzone",
                "BUSCamerone", "BUSInternetvaluation",
                "BUSEvaluation", "BUSClicnction",
                "BUSClicfunction", "BUSaccemera",
                "BUSNogister", "BUSAlreagin",
                "BUSMailww", "BUSpasswords",
                "BUSonlines", "BUSThelationsh",
                "BUSPrivrmissinament",
                "BUSPersonalervice", "BUSAllomendsc",
                "BUSAccesocation", "BUSUseunctions",
                "BUSEnabled", "BUSGtting",
                "BUSAccesphotos",
                "BUSUseddbackunction", "BUSAccesphone",
                "BUSUsedtrips", "BUSAccesermission",
                "BUSUsedunctions", "BUSTurpage",
                "BUSFanwitch", "BUSLighan",
                "BUSOscillatiitch", "BUSReversitch",
                "BUSSwitcttings", "BUScolhhight",
                "BUSwarmight", "BUSjumover",
                "BUSdeletecene", "BUSDeletDIY",
                "BUSReba", "BUSExpebate",
                "BUSUsinties", "BUSRebatails",
                "BUSAfteen", "BUSRecoID",
                "BUSProdubate", "BUSAssociaber",
                "BUSHousenumber",
                "BUSAddressAdditionalContent",
                "BUSRecipientCompany",
                "BUSAllfiequired", "BUSbuyordermail",
                "BUSShipordermail",
                "BUSCollectorderarrives",
                "BUSarrivalorder", "BUSAllcommentsw",
                "AllfieldsarerequiredexcepttaxID",
                "Theproducthasbeendiscontinuedandcannotbepurchasedagain",
                "openeen", "feedback", "Buyww",
                "Theginpile", "TimeSetting",
                "statuormalTwo", "QRcode1",
                "Failtoadd", "WindSpeed",
                "Appointment", "CookingPause",
                "Buzzer", "Cannotusecamera",
                "Goregister", "Strinlights", "Sweden",
                "Swedish", "Denmark", "Danish",
                "Norway", "Norwegian", "Fanlight",
                "Finished", "PayAttention", "Timeisup",
                "Preheatcomplete", "Cookisdone",
                "TheughGet", "Thuseenputbox",
                "UserIDQQQ", "optionalQQQ",
                "BUSSubmitorderpay",
                "AlxceptIDQQ", "Thennoegain", "Smeode",
                "onegistraww", "oarlyleaseup",
                "Steptostep", "UseFID", "ThisaceID",
                "cosdwsdaasdo", "FaceIDpermission",
                "Iraagreement", "Seicientlight",
                "Pleaseredcorrect", "Pleaswhethe",
                "Presetmode", "collectdustw",
                "Workinglengthw", "Thfilterlem",
                "mairush", "Keepiarme", "Regisnow",
                "partcampaign", "Nottime",
                "Incampaign", "sentmail",
                "addrecorrectly", "checkmail",
                "Promdetails", "Sorryalnguage",
                "Dehumidifier", "Drymod", "Curren",
                "deviceab", "Automod", "Continuousmod",
                "Sleepode", "Devicefailu", "Goit",
                "no111", "Abnorma", "Vouchercod",
                "QRcodew", "cable", "Putaway",
                "appointmen", "Nighvision",
                "Nightvision", "Colorimage",
                "Intelligent", "Toenablew", "Qcode1",
                "Unsupportedw", "Theapplicationw",
                "Savethw", "daysincidaw",
                "daysincidsff", "camera_setting_cjwt",
                "longpressww", "Recipeew", "Loadin",
                "Nodata", "Loadingy", "Timingf",
                "Found1", "Searchw", "localnetw2",
                "removedyo", "cancellyo", "switch1w",
                "switch2w", "familynamew",
                "apposition", "approvalem",
                "approvallcam", "approvllam", "Step1",
                "Step2", "Step3", "Step4", "Step5",
                "Step6", "Step7", "Step8", "Step9",
                "Step10", "Step11", "Step12",
                "Whydoesitnotconnect",
                "Pleasecheckifyourrouter", "Steakw",
                "Use8_16characterswi", "longpress", "Longpress",
                "definition_low", "definition_mid", "definition_high", "tv_cruise_functioning",
                "common_permission_goto", "common_permission_fail_3", "buzzing", "Afteilurestore", "BUSSmeode"]

    # print("it条数:" + calculateKeyCount(os.path.join(getPwd(), "total"), "it_final.xml"),targkeys)
    # print("da条数:"+calculateKeyCount(os.path.join(getPwd(), "total"), "da_final.xml"))
    # print("nl条数："+calculateKeyCount(os.path.join(getPwd(), "total"), "strings-nl.xml"))
    # print("pl条数：" + calculateKeyCount(os.path.join(getPwd(), "total"), "strings-pl.xml"))
    # print("pt条数：" + calculateKeyCount(os.path.join(getPwd(), "total"), "strings-pt.xml"))
    # print("en条数：" + calculateKeyCount(os.path.join(getPwd(), "total"), "strings-en.xml"))
    # print("es条数：" + calculateKeyCount(os.path.join(getPwd(), "total"), "strings-es.xml"))
    # print("zh条数：" + calculateKeyCount(os.path.join(getPwd(), "total"), "strings-zh.xml"))
    # print("----------------------------------es文件缺少 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "strings-es.xml",targkeys))
    # print("----------------------------------es文件缺少 end --------------------------------")
    #
    # print("----------------------------------en文件缺少 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "strings-en.xml", targkeys))
    # print("----------------------------------en文件缺少 end --------------------------------")
    #
    # print("----------------------------------zh文件缺少 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "strings-zh.xml", targkeys))
    # print("----------------------------------zh文件缺少 end --------------------------------")

    # print("----------------------------------it 文件缺少 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "it_final.xml", targkeys))
    # print("----------------------------------it 文件缺少 end --------------------------------")

    # print("----------------------------------nl文件多出 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "strings-nl.xml", targkeys))
    # print("----------------------------------nl文件多出 end --------------------------------")

    # print("----------------------------------pl文件多出 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "strings-pl.xml", targkeys))
    # print("----------------------------------pl文件缺少 end --------------------------------")
    #
    # print("----------------------------------pt文件多出 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "strings-pt.xml", targkeys))
    # print("----------------------------------pt文件多出 end --------------------------------")

    # print("----------------------------------da 文件缺少 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "da_final.xml", targkeys))
    # print("----------------------------------da 文件缺少 end --------------------------------")
    #
    # print("----------------------------------hu 文件缺少 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "hu_final.xml", targkeys))
    # print("----------------------------------hu 文件缺少 end --------------------------------")

    # print("----------------------------------hu 文件缺少 start --------------------------------")
    # print(calculateKeyisLack(os.path.join(getPwd(), "total"), "nb_final.xml", targkeys))
    # print("----------------------------------hu 文件缺少 end --------------------------------")
    # cal()
